language: php
 
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
 
before_script:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text

notifications:
    on_success: never
    on_failure: always
